In [39]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [40]:
env = gym.make("FrozenLake-v1")

In [41]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n
q_table = np.zeros((state_space_size,action_space_size))

In [42]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_factor = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.001
exploration_decay_rate = 0.001

In [43]:
rewards_all_episodes = []

#Q-learning algorithm

for episodes in range(num_episodes):
    state = env.reset()
    
    done = False
    rewards_current_episode = 0
    
    
    for step in range(max_steps_per_episode):
        
        #balancing exploratision and exploitation
        exploration_rate_threshold = random.uniform(0,1)
        
        
        if(exploration_rate_threshold > exploration_rate):
            action = np.argmax(q_table[state,:])
        
        else:
            action = env.action_space.sample()
            
        new_state, reward, done , info = env.step(action)
        
        #Update the Q_table
        q_table[state, action] = q_table[state, action]*(1 - learning_rate)+ learning_rate*(reward + discount_factor *np.max(q_table[new_state,:]))
        
        state  = new_state
        rewards_current_episode += reward
        
        if done == True:
            break
            
        #decaying exploration rate
    exploration_rate = min_exploration_rate + (max_exploration_rate)*np.exp(-exploration_decay_rate*episodes)
    rewards_all_episodes.append(rewards_current_episode)

#calculate the reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),10)
count = 1000

#print("*************** avarage rewards per thousand episodes*******************")

for r in rewards_per_thousand_episodes:
    print(count, ":" , str(sum(r/1000)))
    count +=1000
    
print("\n\n************the updated Q_table**************")
print(q_table)

1000 : 0.05200000000000004
2000 : 0.21200000000000016
3000 : 0.45100000000000035
4000 : 0.5440000000000004
5000 : 0.6920000000000005
6000 : 0.6970000000000005
7000 : 0.7300000000000005
8000 : 0.7380000000000005
9000 : 0.7060000000000005
10000 : 0.7160000000000005


************the updated Q_table**************
[[0.52309369 0.46029748 0.45153097 0.45000715]
 [0.30114307 0.32770515 0.31468257 0.48173902]
 [0.40550254 0.4032784  0.4104397  0.43521966]
 [0.29302752 0.3015174  0.24383406 0.40470216]
 [0.54548912 0.40658582 0.46005282 0.34840971]
 [0.         0.         0.         0.        ]
 [0.14238577 0.13648606 0.37504802 0.09838243]
 [0.         0.         0.         0.        ]
 [0.41532084 0.41883935 0.33816037 0.56487909]
 [0.41308245 0.64068778 0.33203834 0.43682771]
 [0.63097623 0.3825795  0.33487664 0.33247613]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.56644764 0.44488021 0.73791332 0.42840888]
 [0.72696156 0.89673449 0.7105

In [44]:
for episode in range(3):
    state = env.reset()
    done = False
    print("*********Episode ",episode+1 ," ********\n\n\n")
    time.sleep(0.5)
    
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state,:])
        new_state, reward,done, info = env.step(action)
        if done:
            clear_output(wait=True)
            env.render()

            if reward == 1:
                print("***** You reached the goal! ****")
                time.sleep(2)

            else:
                print("********You fell into a hole! ********")
                time.sleep(2)

            clear_output(wait=True)
            break

        state = new_state

env.close()

***** You reached the goal! ****
